Repository ArmandBriere/Archy, pull requests merged in 2022-06, with the labels that each got.

#21 + Add gif support by checking if froge is animated
  src/functions/froge/froge.go
Labels: enhancement, golang

#18 + Increment message_count on exp
  src/functions/exp/main.py
  src/tests/functions/exp/test_exp.py
Labels: python

#27 Web firesotre read limit and simple home page
  web/src/app/home-page/home-page.component.html
  web/src/app/home-page/home-page.component.scss
  web/src/app/leaderboard/leaderboard.component.html
  web/src/app/leaderboard/leaderboard.component.scss
  web/src/app/leaderboard/leaderboard.service.ts
  web/src/app/leaderboard/user.interface.ts
  web/src/app/shared/shell/shell.component.html
  web/src/assets/img/Discord-Logo-White.svg
  web/tsconfig.json
Labels: bug, enhancement, web

#28 Feature/add help command
  src/.isort.cfg
  src/functions/help/main.py
  src/functions/help/requirements.txt
  terraform/main.tf
Labels: enhancement, python
