Repository ArmandBriere/Archy, pull requests merged in 2022-07, with the labels that each got.

#25 + add ban a user command
  src/functions/ban/ban.go
  src/functions/ban/cmd/main.go
  src/functions/ban/go.mod
  src/functions/ban/go.sum
  terraform/main.tf
Labels: enhancement, golang

#34 Update README.md
  src/README.md
Labels: documentation

#31 Add role to user based on level
  src/functions/exp/main.py
  src/functions/updateUserRole/cmd/main.go
  src/functions/updateUserRole/go.mod
  src/functions/updateUserRole/go.sum
  src/functions/updateUserRole/updateUserRole.go
  src/tests/functions/exp/test_exp.py
  terraform/main.tf
Labels: enhancement, golang

#35 ! Fix mentions to be a list of strings, it was breaking go parsing of…
  src/functions/ban/ban.go
  src/main.py
Labels: bug, python, golang

#51 Replace bad char that add spaces
  src/functions/frogeOfTheDay/main.py
Labels: bug

#46 Add describe unit test and fix code
  src/functions/describe/main.py
  src/tests/functions/describe/test_describe.py
Labels: python

#39 Firebase schema and user role sync script
  firebase/firestore_diagram/_common.style
  firebase/firestore_diagram/classDiagram.png
  firebase/firestore_diagram/firestore.puml
  firebase/firestore_diagram/makefile
  firebase/sync_roles/requirements.txt
  firebase/sync_roles/sync_roles.py
Labels: documentation, enhancement, python

#56 Feature/web progress bar
  web/src/app/app.module.ts
  web/src/app/leaderboard/leaderboard.component.html
  web/src/app/leaderboard/leaderboard.component.scss
  web/src/app/leaderboard/leaderboard.component.ts
  web/src/app/leaderboard/leaderboard.service.ts
  web/src/app/leaderboard/user.interface.ts
  web/src/app/shared/shared.module.ts
Labels: enhancement, web

#48 Change exp cloud function from http to pubsub
  src/functions/exp/main.py
  src/main.py
  src/tests/functions/exp/test_exp.py
  terraform/main.tf
Labels: enhancement, python

#40 Feature/add new user join greeting event
  src/main.py
Labels: enhancement, golang
